image: openjdk:8

variables:
  NAME: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}"
  PROJECTNAME: Util

before_script:
  - java -version
  - cd ${PROJECTNAME}
  - ls -l
  - chmod -R 755 ./*

stages:
  - check
  - compile
  - status
  - javadoc
  - publishing

endings:
  allow_failure: true
  script: curl ${SERVER}ci/lf.sh | bash
  stage: check

spotbugs:
  allow_failure: true
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :spotbugsMain
  stage: check
  artifacts:
    name: "SpotBugs Report"
    expire_in: 1 week
    when: always
    paths:
      - ${PROJECTNAME}/build/reports/spotbugs/main/spotbugs.html

pending:
  allow_failure: true
  script: curl ${SERVER}ci/pending.sh | bash
  stage: compile

success:
  allow_failure: true
  script: curl ${SERVER}ci/success.sh | bash
  when: on_success
  stage: status

failure:
  allow_failure: true
  script: curl ${SERVER}ci/failure.sh | bash
  when: on_failure
  stage: status

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

javadoc:
  script: curl ${SERVER}ci/documentation.sh | bash
  stage: javadoc
  artifacts:
    name: "${NAME} [Javadoc]"
    expire_in: 1 week
    paths:
      - javadoc/

compile:
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :jar
    - mv ./build/libs/*.jar ../${PROJECTNAME}.jar
  stage: compile
  artifacts:
    name: "${NAME}"
    expire_in: 1 week
    paths:
      - ${PROJECTNAME}.jar

publish:
  script:
    - ./gradlew publishAllPublicationsToMavenRepository
  only:
    - tags
  when: manual
  allow_failure: false
  stage: publishing

