image: openjdk:8

variables:
  PROJECTNAME: "Util"

before_script:
  - java -version
  - ls -l
  - cd ${PROJECTNAME}
  - chmod -R 755 ./*
  - ./gradlew -g ./cache -PnexusSnapshots=${NEXUS_SNAPSHOTS} setupCIWorkspace

stages:
  - compile
  - status
  - javadoc
  - publish
  
pending:
  allow_failure: true
  script:
    - curl ${SERVER}ci/status.sh | bash -s ${PROJECTNAME} ${CI_COMMIT_SHA} pending
  stage: compile

success:
  allow_failure: true
  script:
    - curl ${SERVER}ci/status.sh | bash -s ${PROJECTNAME} ${CI_COMMIT_SHA} success
  when: on_success
  stage: status

failure:
  allow_failure: true
  script:
    - curl ${SERVER}ci/status.sh | bash -s ${PROJECTNAME} ${CI_COMMIT_SHA} failure
  when: on_failure
  stage: status

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc

javadoc:
  script:
    - mkdir ../javadoc
    - ./gradlew javadoc
    - mv ./build/docs/javadoc ../javadoc
  stage: javadoc
  environment: javadoc
  artifacts:
    name: "$PROJECTNAME"
    expire_in: 1 week
    paths:
      - javadoc/

compile:
  script:
    - ./gradlew jar
    - mv ./build/libs/* ../
  stage: compile
  environment: builds
  artifacts:
    name: "${PROJECTNAME}"
    expire_in: 1 week
    paths:
      - ${PROJECTNAME}-*.jar