/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_roanh_util_FileSelector */

#ifndef _Included_dev_roanh_util_FileSelector
#define _Included_dev_roanh_util_FileSelector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_roanh_util_FileSelector
 * Method:    showNativeFileOpen
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_roanh_util_FileSelector_showNativeFileOpen
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dev_roanh_util_FileSelector
 * Method:    showNativeFolderOpen
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_roanh_util_FileSelector_showNativeFolderOpen
  (JNIEnv *, jclass);

/*
 * Class:     dev_roanh_util_FileSelector
 * Method:    showNativeFileSave
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_roanh_util_FileSelector_showNativeFileSave
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     dev_roanh_util_FileSelector
 * Method:    registerNativeFileExtension
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dev_roanh_util_FileSelector_registerNativeFileExtension
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
